### ISSUE TITLE
Pass Data into the Card

### ISSUE THREAD

**Issue by peterbsmith2** [peterbsmith2/south-side-stand#20]
### Time-bound

"Specific Adaptation to Imposed Demand" means that you get good at what you practice. If you read tutorials you get better at reading tutorials. If you write code you get better at writing code.

**Comment by lannonbr** [comment]
This is a relevant section on the Gatsby docs tutorial on how to use props with components: https://www.gatsbyjs.org/tutorial/part-one/#-using-sub-components

**Comment by lannonbr** [comment]
Also a link from React's docs: https://reactjs.org/docs/components-and-props.html
